#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * Two Factor Authentication for Webconfig.
 *
 * @category   apps
 * @package    two-factor-auth
 * @subpackage scripts
 * @author     eGloo <team@egloo.ca>
 * @copyright  2017 Avantech
 * @license    http://www.gnu.org/copyleft/lgpl.html GNU Lesser General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/two_factor_auth/
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('two_factor_auth');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\two_factor_auth\Two_Factor_Auth as Two_Factor_Auth;

clearos_load_library('two_factor_auth/Two_Factor_Auth');

// Exceptions
//-----------

use \Exception as Exception;

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

//--------------------------------------------------------------------
// Command line options
//--------------------------------------------------------------------

$short_options  = 'u:';
$short_options  .= 'p';
$short_options  .= 'y';
$short_options  .= 'n';

// Common
$short_options .= 'h';   // Help

$helpopts  = '
  Common Options
  --------------
  -prompt:    echo prompt in locale
  -match:     echo match in locale
  -mismatch:  echo mismatch in locale
  -u:         username
  -h:         help
';

// Handle command line options
//----------------------------

$options = getopt($short_options);

if (isset($options['p'])) {
    echo lang('two_factor_auth_cli_prompt') . "\n";
    exit(0);
}
if (isset($options['y'])) {
    echo lang('two_factor_auth_otp_match') . "\n";
    exit(0);
}
if (isset($options['n'])) {
    echo lang('two_factor_auth_otp_mismatch') . "\n";
    exit(0);
}

$help = isset($options['h']) ? TRUE : FALSE;

if ($help) {
    echo "usage: " . $argv[0] . " [options]\n";
    echo $helpopts;
    exit(1);
}

$username = isset($options['u']) ? $options['u'] : NULL;

if ($username == NULL) {
    echo lang('two_factor_auth_invalid_user') . "\n";
    exit(1);
}
$two_factor_auth = new Two_Factor_Auth();

try {
    if (!$two_factor_auth->get_require_ssh())
        exit(0);

    if ($username == 'root' && $two_factor_auth->get_root_enabled()) {
        echo $two_factor_auth->get_verification_code($username, TRUE, FALSE);
        exit(0);
    } else if ($username != 'root') {
        $response = $two_factor_auth->api('ssh_login', ['username' => $username]);
        if ($response->code != 0)
            throw new Exception ($response->errmsg);
        exit(0);
    }
    exit(0);
} catch (Exception $e) {
    echo clearos_exception_message($e) . "\n";
    exit(1);
}

// vim: syntax=php
